### ISSUE TITLE
可以增加点赞、分享功能吗

### ISSUE THREAD

**Issue by ShotoZhao** [changbin1997/MWordStar#1]

**Comment by ShotoZhao** [comment]
> 可以考虑增加，不过需要一点时间。

点了赞，但是没反应。要设置什么东西吗？

**Comment by changbin1997** [comment]
应该有反应的吧，你可以到我的博客去试试，同一篇文章短时间内只能点赞一次。

**Comment by ShotoZhao** [comment]
> 应该有反应的吧，你可以到我的博客去试试，同一篇文章短时间内只能点赞一次。

你的可以点赞，但是我的不行，不知道为什么

**Comment by changbin1997** [comment]
我又测试了一下，无论是线上还是本地环境都没问题。你在点赞之前可以按 ctrl + F5 刷新一下，或者也可以清一下浏览器的缓存，浏览器可能缓存了之前的 JS 文件。

**Comment by ShotoZhao** [comment]
> 我又测试了一下，无论是线上还是本地环境都没问题。你在点赞之前可以按 ctrl + F5 刷新一下，或者也可以清一下浏览器的缓存，浏览器可能缓存了之前的 JS 文件。

可以，清除缓存就行了。

**Comment by ShotoZhao** [comment]
> 我又测试了一下，无论是线上还是本地环境都没问题。你在点赞之前可以按 ctrl + F5 刷新一下，或者也可以清一下浏览器的缓存，浏览器可能缓存了之前的 JS 文件。

点赞之后 应该显示红色吧233

**Comment by changbin1997** [comment]
配色问题等我有时间的时候在研究一下吧
