### ISSUE TITLE
代码行数和复制、深色模式功能建议

### ISSUE THREAD

**Issue by tianluanchen** [changbin1997/MWordStar#22]
这是一个很好的typecho主题，希望代码块能增加显示行数和复制的功能，页面实现浅深色模式切换，
👍赞🏅

**Comment by changbin1997** [comment]
这个主题已经有 5 套配色，现在已经不太好增加深色配色了，如果需要包含深浅色的主题的话可以看一下 https://github.com/changbin1997/Facile

**Comment by tianluanchen** [comment]
@changbin1997 我使用了你的Facile主题，效果很棒，但是没有看到深色模式的切换功能，前台和后台都没有，使用的就是release的1.0版本

**Comment by changbin1997** [comment]
包含深色配色的版本还没有打包到 Releases ，如果现在需要用的话只能克隆项目使用。
