### ISSUE TITLE
开发版要去哪里下载？作者的github仓库只有正式版

### ISSUE THREAD

**Issue by wuzhuwei111** [changbin1997/MWordStar#24]
如题

**Comment by changbin1997** [comment]
开发版就是仓库里提交的版本，你可以直接克隆或下载 zip 包，发行版就是我打包过的版本，可以在 https://github.com/changbin1997/MWordStar/releases 下载

**Comment by wuzhuwei111** [comment]
我明白了，还是开发版比较好用，期待更新，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "changbin1997/MWordStar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月16日(星期二) 上午9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [changbin1997/MWordStar] 开发版要去哪里下载？作者的github仓库只有正式版 (Issue #24)





 
开发版就是仓库里提交的版本，你可以直接克隆或下载 zip 包，发行版就是我打包过的版本，可以在 https://github.com/changbin1997/MWordStar/releases 下载
