### ISSUE TITLE
开启emoji表情之后不显示

### ISSUE THREAD

**Issue by ma3252788** [changbin1997/MWordStar#9]
开启emoji之后，只要评论里带有emoji，评论内容就会变成空白。文字也会消失，如果是纯文字评论就是正常的。

![](https://ypyssl.machunjie.com/machunjie/20200602005014.png)

**Comment by changbin1997** [comment]
可能是你的 MySQL 编码不支持 Emoji，可以参考下面几篇文章设置 MySQL 和 Typecho：

* https://get233.com/archives/show-emoji-in-typecho.html
* https://blog.csdn.net/YiferHuang/article/details/86585961
* https://www.moidea.info/archives/how-to-set-up-typecho-blog-to-support-emoji-expression.html

**Comment by ma3252788** [comment]
> 可能是你的 MySQL 编码不支持 Emoji，可以参考下面几篇文章设置 MySQL 和 Typecho：
> 
> * https://get233.com/archives/show-emoji-in-typecho.html
> * https://blog.csdn.net/YiferHuang/article/details/86585961
> * https://www.moidea.info/archives/how-to-set-up-typecho-blog-to-support-emoji-expression.html

感谢~~成功显示啦~~
